### ISSUE TITLE
No check to see if customer doesn't exist

### ISSUE THREAD

**Issue by AchuAchuG** [Aftaab99/OfflineSignatureVerification#9]
While clicking verify I am getting error that Something wrong with the server and in terminal, I got "NoneType" object is not iterable in the line 
anchor_images = [Image.open(BytesIO(x)) for x in get_file_from_db(buffer(customer_id))]

**Comment by Aftaab99** [comment]
Hi, thanks for reporting. I guess its because you haven't uploaded the sample signatures for that particular customer. I should've added a check for that and display a proper message but I kind of forgot to do that. 
Here's how the web demo works-You upload three sample signatures for a given customer and they get stored in a local SQLite database. Then you have to verify your new signatures. I'll shortly add an error message for this, I'm sorry if the UI is confusing. I'll keep this issue open until that's done.

Sorry if I misunderstood anything.

**Comment by RoshiAchu** [comment]
Is it possible to incorporate signature detection ie)identifying a signature from a document and cropping the image and giving that as third input?

**Comment by RoshiAchu** [comment]
> Hi, thanks for reporting. I guess its because you haven't uploaded the sample signatures for that particular customer. I should've added a check for that and display a proper message but I kind of forgot to do that.
> Here's how the web demo works-You upload three sample signatures for a given customer and they get stored in a local SQLite database. Then you have to verify your new signatures. I'll shortly add an error message for this, I'm sorry if the UI is confusing. I'll keep this issue open until that's done.
> 
> Sorry if I misunderstood anything.

Thank you so much for your reply

**Comment by Aftaab99** [comment]
> Is it possible to incorporate signature detection ie)identifying a signature from a document and cropping the image and giving that as third input?

As of now, no, that's not possible. The code expects cropped signatures.
